version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm start"